# activate mouse mode
set -g mouse on

# simplify horizontal and vertical split hot key
bind -n C-h split-window -h    # Ctrl+H horizontal split
bind -n C-v split-window -v    # 按下 Ctrl+V vertical split
